# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3835e357c22b2e7fc12f5bf219e0ce8e9d397e969892c5b313d8b247f8389eef741bc850c9c0ff603a7c761f4a3708e6aa069d01027d9774668dd44cd233965

test:
  secret_key_base: f3a58a501dd7c5e3d44cdecab6b0b393a16d3f63ebbd35952c7c5f09662d81ccfbd78577e3927105f06c610b9ee625946cc0d9602a2d182a95608a433f395652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
